# ==============================================================================
# main.py
# ------------------------------------------------------------------------------
# PURPOSE:
#   The entry point of the entire application.
#   Creates the FastAPI app, registers all routes, and handles startup/shutdown.
#
# THIS FILE IS INTENTIONALLY SMALL.
# All business logic is in services/.
# All database logic is in repositories/.
# All route logic is in api/routes/.
# main.py only wires everything together.
#
# HOW TO RUN:
#   DEVELOPMENT:
#     uvicorn app.main:app --reload
#     uvicorn app.main:app --reload --reload-dir app
#
#   PRODUCTION (Local):
#     gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker
#
#   PRODUCTION (Render):
#     gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${PORT}
#
# API DOCS (auto-generated by FastAPI):
#   http://127.0.0.1:8000/docs   → Swagger UI
#   http://127.0.0.1:8000/redoc  → ReDoc UI
#
# ENVIRONMENT VARIABLES:
#   Required: DATABASE_URL, REDIS_URL, GEMINI_API_KEY
#   Optional: SERPER_API_KEY, AWS_* (for S3 storage), DEBUG
#   Load from .env: from dotenv import load_dotenv; load_dotenv()
#
# DEPLOYMENT:
#   - For Render deployment, see: render.yaml
#   - For local secrets, see: .env.example
# ==============================================================================

import logging
import time
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Track module initialization time
_module_init_start = time.time()

# Import settings for app metadata
_settings_start = time.time()
from app.core.config import settings
_settings_time = time.time() - _settings_start

# Import database table creation function
_db_import_start = time.time()
from app.core.database import create_tables
_db_import_time = time.time() - _db_import_start

# Import all route routers
_routes_import_start = time.time()
from app.api.routes import (
    equipment_router,
    job_router,
    source_router,
    health_router,
)
_routes_import_time = time.time() - _routes_import_start

# ==============================================================================
# LOGGING CONFIGURATION
# ------------------------------------------------------------------------------
# Configure logging for the entire application.
# Every file uses logger = logging.getLogger(__name__)
# This config controls what gets shown and where.
# ==============================================================================
logging.basicConfig(
    level=logging.INFO,             # show INFO and above (INFO, WARNING, ERROR)
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)

# Log module initialization timing
_module_init_time = time.time() - _module_init_start
logger.info("🔧 Module initialization complete: %.2fms", _module_init_time * 1000)
logger.info("  → Settings: %.2fms | Database: %.2fms | Routes: %.2fms", 
            _settings_time * 1000, _db_import_time * 1000, _routes_import_time * 1000)


# ==============================================================================
# FASTAPI APPLICATION INSTANCE
# ------------------------------------------------------------------------------
# This is the main FastAPI app object.
# Uvicorn runs this: uvicorn app.main:app
# ==============================================================================
app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    description=(
        "Solar Equipment Intelligence Engine — "
        "Extracts and stores equipment specifications for "
        "US solar installations. Feeds calculation engine and SLD generator."
    ),
    # Only show interactive docs in debug mode
    # WHY: In production you don't want the API docs publicly accessible
    docs_url="/docs" if settings.DEBUG else None,
    redoc_url="/redoc" if settings.DEBUG else None,
)


# ==============================================================================
# CORS MIDDLEWARE
# ------------------------------------------------------------------------------
# CORS = Cross-Origin Resource Sharing.
# Controls which domains are allowed to call this API from a browser.
#
# WHY: If your PMS frontend is on a different domain than this API,
# the browser will block the request unless CORS is configured.
#
# In development we allow all origins (*).
# In production you should restrict to your actual PMS domain.
# ==============================================================================

# Add timing middleware (must be added first, so it runs last in the chain)
from fastapi.requests import Request
from fastapi.responses import Response

@app.middleware("http")
async def add_process_time_header(request: Request, call_next):
    """Middleware to track request processing time"""
    start_time = time.time()
    response = await call_next(request)
    process_time = time.time() - start_time
    response.headers["X-Process-Time"] = str(process_time)
    logger.debug(f"🕐 {request.method} {request.url.path} → {process_time*1000:.2f}ms (status: {response.status_code})")
    return response

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"] if settings.DEBUG else ["https://your-pms-domain.com"],
    allow_credentials=True,
    allow_methods=["*"],    # allow GET, POST, DELETE, etc.
    allow_headers=["*"],    # allow all headers
)


# ==============================================================================
# STARTUP EVENT
# ------------------------------------------------------------------------------
# Runs ONCE when the application starts.
# Creates all database tables if they don't exist yet.
# Validates critical configuration settings.
#
# WHY ON STARTUP:
#   Tables are created from SQLAlchemy models automatically.
#   This means you don't need to manually write SQL or run migrations
#   for the initial setup.
#   If a table already exists, SQLAlchemy skips it safely.
#   Configuration validation happens before anything else.
# ==============================================================================
@app.on_event("startup")
def startup():
    startup_start_time = time.time()
    logger.info("=" * 70)
    logger.info("🚀 Starting %s v%s", settings.APP_NAME, settings.APP_VERSION)
    logger.info("=" * 70)
    
    # Check configuration
    config_start = time.time()
    logger.info("📋 Checking configuration...")
    logger.info("  Database configured: %s", "✓" if settings.DATABASE_URL else "✗")
    logger.info("  Gemini API configured: %s", "✓" if settings.GEMINI_API_KEY else "✗")
    logger.info("  Serper API configured: %s", "✓" if settings.SERPER_API_KEY else "✗")
    logger.info("  Redis configured: %s", "✓" if settings.REDIS_URL else "✗")
    config_time = time.time() - config_start
    logger.info("  ⏱️ Configuration check: %.2fms", config_time * 1000)
    
    # Create database tables
    db_start = time.time()
    logger.info("💾 Creating database tables if they don't exist...")
    try:
        create_tables()
        db_time = time.time() - db_start
        logger.info("  ✓ Database tables ready: %.2fms", db_time * 1000)
    except Exception as e:
        logger.error("  ✗ Failed to create database tables: %s", str(e))
        logger.error("  Check your DATABASE_URL configuration in .env")
        raise
    
    # Routes registration (happens after this function)
    logger.info("🛣️  Registering routes...")
    routes_start = time.time()
    # Note: Routes are registered below, so we'll capture timing there
    
    # Total startup time
    total_startup_time = time.time() - startup_start_time
    logger.info("=" * 70)
    logger.info("✅ Application startup complete: %.2fms | %.2fs", 
                total_startup_time * 1000, total_startup_time)
    logger.info("=" * 70)


# ==============================================================================
# SHUTDOWN EVENT
# ------------------------------------------------------------------------------
# Runs ONCE when the application shuts down (CTRL+C or server restart).
# Used to cleanly close any open connections.
# ==============================================================================
@app.on_event("shutdown")
def shutdown():
    logger.info("Application shutting down...")


# ==============================================================================
# REGISTER ROUTES
# ------------------------------------------------------------------------------
# Include all route routers into the main app.
# Each router has its own prefix defined in its file.
#
# Final URL structure:
#   POST   /equipment/           → extract equipment specs
#   GET    /equipment/           → list all equipment
#   GET    /equipment/{id}       → get one equipment by UUID
#   DELETE /equipment/{id}       → delete equipment
#   GET    /jobs/{job_id}        → check extraction job status
#   GET    /sources/             → list trusted domains
#   POST   /sources/             → add trusted domain
#   DELETE /sources/{domain}     → deactivate trusted domain
#   GET    /health/              → system health check
# ==============================================================================
logger.info("📍 Registering routes...")
routes_start = time.time()
app.include_router(equipment_router)
app.include_router(job_router)
app.include_router(source_router)
app.include_router(health_router)
routes_time = time.time() - routes_start
logger.info("  ✓ Routes registered: %.2fms", routes_time * 1000)


# ==============================================================================
# ROOT ENDPOINT
# ------------------------------------------------------------------------------
# Simple root endpoint — confirms the app is running.
# ==============================================================================
@app.get("/", tags=["Root"])
def root():
    return {
        "app": settings.APP_NAME,
        "version": settings.APP_VERSION,
        "status": "running",
        "docs": "/docs"
    }